### ISSUE TITLE
Kits avec master

### ISSUE THREAD

**Issue by xXjohn96Xx** [pokepixelstaff/pokepixel#12]
ce matin en fesant le kit elite j'ai vu qu'on recevais plus de master , je voulais donc savoir si c'etais possible d'avoir un autre kit avec une master dedans mais qui serais fesable que 1fois par jours , ca evite dans avoir trop mais de quand meme en avoir car on vois un sh ou un dw  ou meme un legendaire on veut pas ce casser la tete un master ca aide

**Comment by Tipoudi** [comment]
kit faisable toutes les 12h avec une master dedans > toujours ok pour les pas gros joueurs et ceux qui se connectent deux fois dans la journée peuvent en avoir un chouya plus

**Comment by Flashback083** [comment]
./kit ball add : 
- 1 Master Ball
- 3 Hyper Ball
- 5 Super Ball
- 10 Poké Ball

Kit utilisable une fois par jour que pour les pokélite actuellement !
