### ISSUE TITLE
Enderchest et inventaire perdus

### ISSUE THREAD

**Issue by Tipoudi** [pokepixelstaff/pokepixel#17]
Liaisons des inventaires donjons / semi rp m'a fait perdre le contenu qu'il me restait, possibilité de le recupérer ?

**Comment by Tipoudi** [comment]
LE contenu était en mp sur discord. Je met ça la pour que tu le vois flash

**Comment by Flashback083** [comment]
Ok, je vais delier temporairement les items en donjons car le plugin pose encore quelques soucis
ta pas acces au gm pour te le regive ?

**Comment by Tipoudi** [comment]
Si mais j'attendais ton aval j'ai réussi à récupérer avec un échange joueur le plus important (non givable au gm) du coup je fais ca, problème réglé du coup !
