### ISSUE TITLE
Messagerie problemes

### ISSUE THREAD

**Issue by Tipoudi** [pokepixelstaff/pokepixel#19]
problèmes dans la messagerie, des fois on ne peux pas /msg /w /r a un joueur, probleme de maps peut être a creuser (la map flat semi rp semble peut etre etre celle qui bug) je me rappelle avoir noté ce bug une journée en donjon aussi

**Comment by Flashback083** [comment]
J'ai fais quelques modif niveau commandes, faudra me dire si le bug est toujours présent
