### ISSUE TITLE
./mc ./sc ./a On ne sait plus ! *clin d'oeil clin d'oeil*

### ISSUE THREAD

**Issue by Tipoudi** [pokepixelstaff/pokepixel#20]
Tout est dans le titre Lequel utilises t-on ?
le /a tout le monde le voit 
le /sc que ceux qui ont la perm
et le /mc pas encore pu test
Voila jte laisse regarder ce qu'on fait de ces commandes ! (perso j'ai l'habitude du /a :p)

**Comment by Flashback083** [comment]
Alors du coup : 
/sc , /staffchat -> Permet de parler dans la conv staffchat, il faut juste que je redem le bungee pour que ça prenne effet sur toi (les perms ne se font plus par groupe mais par user du coup c'est plus chiant à faire)

**Comment by Flashback083** [comment]
Les autres commandes du coup ne sont pas utilisé
