### ISSUE TITLE
Protection des zones evs3 et xp(6leupho)

### ISSUE THREAD

**Issue by JacksHereIM** [pokepixelstaff/pokepixel#21]
est-il possible que quelqu'un securise ces 2 zones, elles sont sous le spawn
il faut que les joueurs ne puissent pas avoir ces commandes dedans
- /sethome
- /spawn
- /tpa
- /tpahere
- /pc
- /pgift

**Comment by Tipoudi** [comment]
+ l'acceptation d'une tp entrante a bloquer je crois que c'est le /tpaccept lorsqu'on clic sur le "oui" de la tp qui s'affiche (a vérifier)
En revanche un pgift exterieur ne sera pas empechable
