### ISSUE TITLE
Bug pixelmon

### ISSUE THREAD

**Issue by Flashback083** [pokepixelstaff/pokepixel#5]
- Impossible de faire prendre des EVS à un pokémon lvl 100 !
    Solution temporaire: Ne pas faire monter son pkmn lvl 100 avant d'avoir fait les EVS. Si votre pokémon est déjà lvl 100, demandez à un admin de vous le mettre lvl 99

**Comment by Nac0u-25** [comment]
```html <div class="style">test</div>```

**Comment by Flashback083** [comment]
Move sur https://github.com/pokepixelserv/pokepixelpublic/issues
