### ISSUE TITLE
Perms Animateur/Dibou

### ISSUE THREAD

**Issue by MrDibou** [pokepixelstaff/pokepixel#6]
Il y a certaine commande d'avant la maintenance que j'aimerais revois dans ma liste de perms ; 
/pcbox slot (permet de voir le contenu de la boite de l'utilisateur de la commande seulement)
/invsee (Pouvoir donner les recompenses)
Interagir avec le wilderness
Les Couleurs dans le chat
le /mc
/ping
D'autre etais dans mes pensé tantot mais suite a un trou de memoire ;D

**Comment by Flashback083** [comment]
Il manque  : 
/pcbox slot
Verifier le /mc car le plugin a été changé
